@php
    $headerMedia = App\Models\HeaderMedia::latest()->get();
@endphp

<div class="relative w-full max-w-xs sm:max-w-sm md:max-w-md lg:max-w-lg xl:max-w-xl mx-auto lg:mx-0 lg:ml-auto px-2 sm:px-0" id="hero-slider">
    
    <!-- Slides Container -->
    <div class="overflow-hidden rounded-2xl sm:rounded-[2rem] md:rounded-[2.5rem] shadow-xl sm:shadow-2xl" id="slides-container">
        <div class="flex transition-transform duration-500 ease-out will-change-transform" id="slider-track">
            
            @if (!empty($headerMedia) && count($headerMedia) > 0)
                @foreach ($headerMedia as $media)
                    <div class="w-full flex-shrink-0 px-2 sm:px-4 md:px-5 py-3 sm:py-4 md:py-5" data-slide>
                        <div class="glass-panel bg-white rounded-xl sm:rounded-2xl md:rounded-3xl overflow-hidden shadow-md">
                            <img src="{{ asset($media->media_path) }}" 
                                 alt="{{ $media->title }}"
                                 class="w-full h-[280px] sm:h-[340px] md:h-[380px] lg:h-[420px] object-cover"
                                 loading="eager">
                            
                            <div class="p-4 sm:p-5 md:p-6 text-center">
                                <p class="font-semibold text-[#1A1A1A] text-base sm:text-lg leading-tight line-clamp-2">
                                    {{ $media->title }}
                                </p>
                                <a href="/discover?search={{ urlencode($media->title) }}" 
                                   class="inline-block mt-3 sm:mt-4 text-xs sm:text-sm font-medium text-[#8B5A2B] hover:text-[#6B3E1A] hover:underline transition-colors">
                                    View deal →
                                </a>
                            </div>
                        </div>
                    </div>
                @endforeach
            @else
                <!-- Fallback -->
                <div class="w-full flex-shrink-0 px-2 sm:px-5 py-3 sm:py-5">
                    <div class="w-full h-[280px] sm:h-[340px] md:h-96 bg-gradient-to-br from-blue-900 to-gray-800 rounded-xl sm:rounded-2xl md:rounded-3xl flex items-center justify-center text-white">
                        <div class="text-center px-4">
                            <h2 class="text-xl sm:text-2xl font-bold">Gallery Coming Soon</h2>
                            <p class="text-sm sm:text-base mt-2">Check back for amazing deals</p>
                        </div>
                    </div>
                </div>
            @endif
        </div>
    </div>

    <!-- Custom Dots -->
    <div class="flex justify-center gap-2 sm:gap-3 mt-4 sm:mt-6 md:mt-8" id="dots-container">
        <!-- Dots will be generated by JavaScript -->
    </div>

    <!-- Navigation Arrows (Responsive positioning) -->
    <button id="prev-btn"
        class="absolute left-0 sm:-left-3 md:-left-4 top-1/2 -translate-y-1/2 bg-white/90 backdrop-blur-sm hover:bg-white shadow-md hover:shadow-lg w-8 h-8 sm:w-9 sm:h-9 md:w-10 md:h-10 rounded-lg sm:rounded-xl md:rounded-2xl flex items-center justify-center text-base sm:text-lg md:text-xl text-gray-700 z-10 transition-all active:scale-95 focus:outline-none focus:ring-2 focus:ring-[#8B5A2B]/50">
        ←
    </button>
    
    <button id="next-btn"
        class="absolute right-0 sm:-right-3 md:-right-4 top-1/2 -translate-y-1/2 bg-white/90 backdrop-blur-sm hover:bg-white shadow-md hover:shadow-lg w-8 h-8 sm:w-9 sm:h-9 md:w-10 md:h-10 rounded-lg sm:rounded-xl md:rounded-2xl flex items-center justify-center text-base sm:text-lg md:text-xl text-gray-700 z-10 transition-all active:scale-95 focus:outline-none focus:ring-2 focus:ring-[#8B5A2B]/50">
        →
    </button>

</div>

<script>
(function() {
    // Wait for DOM to be fully loaded
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', initSlider);
    } else {
        initSlider();
    }

    function initSlider() {
        const sliderContainer = document.getElementById('hero-slider');
        if (!sliderContainer) return;

        const track = document.getElementById('slider-track');
        const slidesContainer = document.getElementById('slides-container');
        const prevBtn = document.getElementById('prev-btn');
        const nextBtn = document.getElementById('next-btn');
        const dotsContainer = document.getElementById('dots-container');
        
        if (!track || !slidesContainer) return;
        
        // Get all slide elements
        let slides = Array.from(document.querySelectorAll('[data-slide]'));
        const totalSlides = slides.length;
        
        // If no slides or only one, hide arrows and dots (optional)
        if (totalSlides === 0) {
            if (prevBtn) prevBtn.style.display = 'none';
            if (nextBtn) nextBtn.style.display = 'none';
            if (dotsContainer) dotsContainer.style.display = 'none';
            return;
        }
        
        if (totalSlides === 1) {
            if (prevBtn) prevBtn.style.display = 'none';
            if (nextBtn) nextBtn.style.display = 'none';
            if (dotsContainer) dotsContainer.style.display = 'none';
            return;
        }
        
        let currentIndex = 0;
        let slideWidth = 0;
        let isTransitioning = false;
        let touchStartX = 0;
        let touchEndX = 0;
        let resizeTimeout;
        
        // Generate dots
        function generateDots() {
            if (!dotsContainer) return;
            dotsContainer.innerHTML = '';
            for (let i = 0; i < totalSlides; i++) {
                const dot = document.createElement('button');
                dot.setAttribute('data-index', i);
                dot.setAttribute('aria-label', `Go to slide ${i + 1}`);
                dot.className = `w-2 h-2 sm:w-2.5 sm:h-2.5 md:w-3 md:h-3 rounded-full transition-all duration-300 ${
                    i === currentIndex ? 'bg-[#8B5A2B] scale-110 shadow-sm' : 'bg-gray-300 hover:bg-gray-400'
                }`;
                dot.addEventListener('click', () => {
                    if (!isTransitioning && i !== currentIndex) {
                        goToSlide(i);
                    }
                });
                dotsContainer.appendChild(dot);
            }
        }
        
        // Update dots active state
        function updateDots() {
            if (!dotsContainer) return;
            const dots = dotsContainer.querySelectorAll('button');
            dots.forEach((dot, idx) => {
                if (idx === currentIndex) {
                    dot.classList.remove('bg-gray-300', 'hover:bg-gray-400');
                    dot.classList.add('bg-[#8B5A2B]', 'scale-110', 'shadow-sm');
                } else {
                    dot.classList.remove('bg-[#8B5A2B]', 'scale-110', 'shadow-sm');
                    dot.classList.add('bg-gray-300', 'hover:bg-gray-400');
                }
            });
        }
        
        // Update slide position
        function updateSliderPosition(animate = true) {
            if (!track || slideWidth <= 0) return;
            
            if (!animate) {
                track.style.transition = 'none';
            } else {
                track.style.transition = 'transform 0.5s ease-out';
            }
            
            const translateX = -currentIndex * slideWidth;
            track.style.transform = `translateX(${translateX}px)`;
            
            // Force reflow when transition is disabled
            if (!animate) {
                // Trigger reflow to apply the transform immediately
                void track.offsetHeight;
                track.style.transition = 'transform 0.5s ease-out';
            }
            
            updateDots();
        }
        
        // Calculate slide width based on container
        function updateSlideWidth() {
            if (!slidesContainer) return 0;
            const containerRect = slidesContainer.getBoundingClientRect();
            // Get width of the first slide (or any slide)
            if (slides.length > 0 && slides[0]) {
                const slideRect = slides[0].getBoundingClientRect();
                return slideRect.width;
            }
            return containerRect.width;
        }
        
        // Recalculate dimensions and reposition
        function recalcAndReposition() {
            const newSlideWidth = updateSlideWidth();
            if (Math.abs(newSlideWidth - slideWidth) > 1) {
                slideWidth = newSlideWidth;
                // Ensure current index is still valid (can be useful if slides changed)
                if (currentIndex >= totalSlides) currentIndex = totalSlides - 1;
                if (currentIndex < 0) currentIndex = 0;
                updateSliderPosition(true);
            } else if (slideWidth <= 0 && newSlideWidth > 0) {
                slideWidth = newSlideWidth;
                updateSliderPosition(true);
            }
        }
        
        // Navigation with wrap-around (infinite loop)
        function goToSlide(index, animate = true) {
            if (isTransitioning) return;
            
            // Handle wrap-around
            if (index >= totalSlides) {
                index = 0;
            } else if (index < 0) {
                index = totalSlides - 1;
            }
            
            if (index === currentIndex) return;
            
            isTransitioning = true;
            currentIndex = index;
            
            updateSliderPosition(animate);
            
            // Reset transition lock after animation ends
            setTimeout(() => {
                isTransitioning = false;
            }, 550); // Slightly longer than transition duration
        }
        
        function nextSlide() {
            if (isTransitioning) return;
            goToSlide(currentIndex + 1);
        }
        
        function prevSlide() {
            if (isTransitioning) return;
            goToSlide(currentIndex - 1);
        }
        
        // Touch/swipe support for mobile
        function handleTouchStart(e) {
            touchStartX = e.touches[0].clientX;
        }
        
        function handleTouchMove(e) {
            if (!touchStartX) return;
            touchEndX = e.touches[0].clientX;
            const deltaX = touchEndX - touchStartX;
            // Allow horizontal swipe only, don't prevent vertical scroll completely
            if (Math.abs(deltaX) > 10) {
                e.preventDefault();
            }
        }
        
        function handleTouchEnd() {
            if (!touchStartX || !touchEndX) {
                touchStartX = 0;
                touchEndX = 0;
                return;
            }
            const deltaX = touchEndX - touchStartX;
            const threshold = 50; // Minimum swipe distance
            
            if (Math.abs(deltaX) > threshold) {
                if (deltaX > 0) {
                    // Swipe right -> previous slide
                    prevSlide();
                } else {
                    // Swipe left -> next slide
                    nextSlide();
                }
            }
            
            // Reset values
            touchStartX = 0;
            touchEndX = 0;
        }
        
        // Add resize listener with debounce
        function handleResize() {
            clearTimeout(resizeTimeout);
            resizeTimeout = setTimeout(() => {
                if (slides.length > 0) {
                    recalcAndReposition();
                }
            }, 150);
        }
        
        // Set up event listeners
        function bindEvents() {
            if (prevBtn) prevBtn.addEventListener('click', prevSlide);
            if (nextBtn) nextBtn.addEventListener('click', nextSlide);
            
            // Touch events for mobile swipe
            const sliderTrackElement = track;
            if (sliderTrackElement) {
                sliderTrackElement.addEventListener('touchstart', handleTouchStart, { passive: false });
                sliderTrackElement.addEventListener('touchmove', handleTouchMove, { passive: false });
                sliderTrackElement.addEventListener('touchend', handleTouchEnd);
            }
            
            window.addEventListener('resize', handleResize);
        }
        
        // Initialize slider dimensions and rendering
        function init() {
            generateDots();
            slideWidth = updateSlideWidth();
            if (slideWidth <= 0) {
                // Fallback: wait a bit and try again
                setTimeout(() => {
                    slideWidth = updateSlideWidth();
                    if (slideWidth > 0) {
                        updateSliderPosition(false);
                        bindEvents();
                    }
                }, 100);
            } else {
                updateSliderPosition(false);
                bindEvents();
            }
        }
        
        // Additional observer for images loading that might affect dimensions
        const images = track.querySelectorAll('img');
        let imagesLoaded = 0;
        if (images.length > 0) {
            const onImageLoad = () => {
                imagesLoaded++;
                if (imagesLoaded === images.length) {
                    // Recalculate after all images have loaded
                    setTimeout(() => {
                        recalcAndReposition();
                    }, 50);
                }
            };
            images.forEach(img => {
                if (img.complete) {
                    onImageLoad();
                } else {
                    img.addEventListener('load', onImageLoad);
                    img.addEventListener('error', onImageLoad); // Still count on error
                }
            });
        }
        
        init();
    }
})();
</script>

