@php
    $headerMedia = App\Models\HeaderMedia::latest()->get();
   @endphp
<div class="relative max-w-md mx-auto lg:mx-0 lg:ml-auto" id="hero-slider">
    
    <!-- Slides Container -->
    <div class="overflow-hidden rounded-[2.5rem] shadow-2xl" id="slides-container">
        <div class="flex transition-transform duration-700 ease-out" id="slider-track">
            
            @if (!empty($headerMedia) && count($headerMedia) > 0)
                @foreach ($headerMedia as $media)
                    <div class="w-full flex-shrink-0 px-5 md:px-6 py-5" data-slide>
                        <div class="glass-panel bg-white rounded-3xl overflow-hidden">
                            <img src="{{ asset($media->media_path) }}" 
                                 alt="{{ $media->title }}"
                                 class="w-full h-[380px] md:h-[420px] object-cover"
                                 loading="eager">
                            
                            <div class="p-6 text-center">
                                <p class="font-semibold text-[#1A1A1A] text-lg leading-tight">
                                    {{ $media->title }}
                                </p>
                                <a href="/discover?search={{ urlencode($media->title) }}" 
                                   class="inline-block mt-4 text-sm font-medium text-[#8B5A2B] hover:underline">
                                    View deal →
                                </a>
                            </div>
                        </div>
                    </div>
                @endforeach
            @else
                <!-- Fallback -->
                <div class="w-full flex-shrink-0 px-5 py-5">
                    <div class="w-full h-96 bg-gradient-to-br from-blue-900 to-gray-800 rounded-3xl flex items-center justify-center text-white">
                        <div class="text-center">
                            <h2 class="text-2xl font-bold">Gallery Coming Soon</h2>
                        </div>
                    </div>
                </div>
            @endif
        </div>
    </div>

    <!-- Custom Dots -->
    <div class="flex justify-center gap-3 mt-8" id="dots-container">
        <!-- Dots will be generated by JavaScript -->
    </div>

    <!-- Optional: Left & Right Arrows -->
    <button id="prev-btn"
        class="absolute -left-4 top-1/2 -translate-y-1/2 bg-white shadow-lg hover:bg-gray-50 w-10 h-10 rounded-2xl flex items-center justify-center text-xl z-10 transition-all active:scale-95">
        ←
    </button>
    
    <button id="next-btn"
        class="absolute -right-4 top-1/2 -translate-y-1/2 bg-white shadow-lg hover:bg-gray-50 w-10 h-10 rounded-2xl flex items-center justify-center text-xl z-10 transition-all active:scale-95">
        →
    </button>

</div>